platform :ios, '6.0' 
pod 'SHPopoverControllerBlocks', :path => '../'
pod 'SHBarButtonItemBlocks'
pod 'SHControlBlocks'

target :ExampleTests do
  pod 'SHTestCaseAdditions', :git => "https://github.com/seivan/SHTestCaseAdditions"
  pod "KIF-next"
end
