platform :ios, '7.0' 

link_with [:Sample, :Tests]
pod 'SHPopoverControllerBlocks', :path => '../'

target :Sample, :exclusive => true do
  pod 'SHBarButtonItemBlocks'
  pod 'SHControlBlocks'
end

target :Tests, :exclusive => true do
  pod 'SHTestCaseAdditions'
  pod "KIF/XCTest", :git => "https://github.com/tonyd256/KIF", :branch => "xctest"
end





